In [50]:
import pandas as pd
df=pd.read_csv('/content/KAG_Conversion_Data.csv')

In [51]:
df.head()

ad_id  xyz_campaign_id  ...  Total_Conversion Approved_Conversion
0  708746              916  ...                 2                   1
1  708749              916  ...                 2                   0
2  708771              916  ...                 1                   0
3  708815              916  ...                 1                   0
4  708818              916  ...                 1                   1

[5 rows x 11 columns]

In [92]:
import numpy as np
data_file ='/content/KAG_Conversion_Data.csv'
data = np.genfromtxt(data_file, delimiter=",", skip_header=1,dtype=int)
data_float=np.genfromtxt(data_file, delimiter=",", skip_header=1)
data_str=np.genfromtxt(data_file,delimiter=',',skip_header=1,dtype=str)
# printing the data

print("\nData: \n\n", data)






Data: 

 [[ 708746     916  103916 ...      -1       2       1]
 [ 708749     916  103917 ...      -1       2       0]
 [ 708771     916  103920 ...       0       1       0]
 ...
 [1314412    1178  179979 ...      -1       2       0]
 [1314414    1178  179981 ...      -1       8       2]
 [1314415    1178  179982 ...      -1       5       2]]


In [53]:
#How many unique ad campaigns (xyzcampaignid) does this data contain ? And for how many times was each campaign run ?

unique_ids=np.unique(data[: ,1])
unique_ids

array([ 916.,  936., 1178.])

In [54]:
len(unique_ids)

3

In [55]:
len(data[data[:,1]==916])

54

In [56]:
len(data[data[:,1]==936])

464

In [57]:
len(data[data[:,1]==1178])

625

In [83]:
#What are the age groups that were targeted through these ad campaigns?
age_groups= str(data[:,3])
age_groups

'[nan nan nan ... nan nan nan]'

In [59]:
np.unique(age_groups)

array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11')

In [60]:
#What was the average, minimum and maximum amount spent on the ads?
ads_amount=np.round(data_float[ :,8],2)
ads_amount



array([  1.43,   1.82,   0.  , ...,  40.29, 198.71, 165.61])

In [61]:
ads_amount.mean()

51.360656167979

In [62]:
print(ads_amount.max())
ads_amount.min()

639.95


0.0

In [67]:
# What is the id of the ad having the maximum number of clicks

max_clicks=np.max(data[:,7])
print(max_clicks)
max_id =int(data[:,0][data[:,7]==421])
print(max_id)

421.0
1121814


In [77]:
#How many people bought the product after seeing the ad with most clicks? Is that the maximum number of purchases in this dataset?
Pur_max_id= int(data[:,10][data[:,7]==421])
print(Pur_max_id)
np.max(data[:,10])

13


21.0

In [97]:
#So the ad with the most clicks didn't fetch the maximum number of purchases. Find the details of the product having maximum number of purchases
prod_max=data[data[:,10]==21]
prod_max


array([[1121104,    1178,  144533,      -1,      -1,      16, 2080666,
            202,      -1,      40,      21]])